spring:
  datasource:
    url: "jdbc:postgresql://localhost:5433/betapp"
    username: "betapp"
    password: "betapp"
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
  flyway:
    enabled: true
    locations: "classpath:db/migration"

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "health,info"
