spring:
  flyway:
    enabled: false
  datasource:
    url: "jdbc:postgresql://localhost:5433/betapp"
    username: "betapp"
    password: "betapp"
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "health,info"
